# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell" #default
#ZSH_THEME="mh" #[tylern:~]$
#ZSH_THEME="miloshadzic"
if [[ -n $SSH_CONNECTION ]]; then
   #export ZSH_THEME="agnoster"
   export ZSH_THEME="my"
   #export ZSH_THEME="bullet-train"
else
   #export ZSH_THEME="agnoster"
   export ZSH_THEME="gallois"
   #export ZSH_THEME="gallifrey"
   #export ZSH_THEME="my"
fi

#ZSH_THEME="agnoster"
DEFAULT_USER="tylern"
ulimit -n 4000

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git svn rsync)


export PATH="/usr/local/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

source $ZSH/oh-my-zsh.sh

export ROOTSYS=/usr/local/root
export PATH=$ROOTSYS/bin:$PATH
export PYTHONDIR=$ROOTSYS
export LD_LIBRARY_PATH=$ROOTSYS/lib:$PYTHONDIR/lib:$ROOTSYS/bindings/pyroot:$LD_LIBRARY_PATH 
export PYTHONPATH=$ROOTSYS/lib:$ROOTSYS/build/lib:$ROOTSYS/bindings/pyroot
export LD_LIBRARY_PATH=$ROOTSYS/lib:$PYTHONDIR/lib:$LD_LIBRARY_PATH

export MYSQLLIB=/usr/lib64/mysql
export TCLINC=/usr/include/tcl
export MYSQLINC=/usr/include/mysql

export LD_LIBRARY_PATH=/lib:$LD_LIBRARY_PATH
export PYTHIA=/usr/local/pythia
export PYTHIA8=$PYTHIA/pythia8
export PYTHIA8DATA=$PYTHIA8/share/Pythia8/xmldoc
export PYTHONPATH=$PYTHONPATH:$PYTHIA8/lib
export LD_LIBRARY_PATH=$PYTHONDIR/lib:$LD_LIBRARY_PATH

